- id: fp-ceph-kraken-conf
  role: ['ceph-osd','controller','primary-controller']
  type: puppet
  version: 2.0.0
  parameters:
    puppet_manifest: puppet/manifests/conf.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600
  requires: ['post_deployment_start']
  required_for: ['ceph_ready_check']
