#- id: ceph-osd
#  role: ['ceph-osd']
#  type: skipped
#  version: 2.0.0
#- id: top-role-ceph-osd
#  role: ['ceph-osd']
#  type: skipped
#  version: 2.0.0
- id: ceph-compute
  role: ['ceph-osd']
  type: skipped
  version: 2.0.0
- id: fp-ceph-kraken-repo-del
  role: ['controller','primary-controller']
  type: puppet
  version: 2.0.0
  parameters:
    puppet_manifest: puppet/manifests/repo_del.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600
  requires: ['deploy_start']
  required_for: ['globals','ceph-mon','primary-ceph-mon']
- id: fp-ceph-kraken-packages
  role: ['controller','primary-controller','ceph-osd']
  type: puppet
  version: 2.0.0
  parameters:
    puppet_manifest: puppet/manifests/packages.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600
  cross-depends:
  - name: 'primary-ceph-mon'
    role: ['primary-controller','controller']
#  cross-depended-by:
#    - name: 'fp-ceph-kraken-osd'
- id: fp-ceph-kraken-keyring-fix
  role: ['controller','primary-controller']
  type: puppet
  version: 2.0.0
  parameters:
    puppet_manifest: puppet/manifests/keyring_fix.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600
#  cross-depends:
#  - name: 'fp-ceph-kraken-packages'
#    role: ['primary-controller','controller']
  requires: ['fp-ceph-kraken-packages']
  required_for: ['fp-ceph-kraken-conf']
- id: fp-ceph-kraken-ceph-compute
  role: ['ceph-osd']
  type: puppet
  version: 2.0.0
  parameters:
    cwd: /
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/ceph/ceph_compute.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600
  requires: ['fp-ceph-kraken-packages']
  required_for: ['ceph-osd']
  cross-depends:
  - name: 'fp-ceph-kraken-keyring-fix'
  cross_depended_by:
  - name: ceph_ready_check
#- id: fp-ceph-kraken-osd
#  role: ['ceph-osd']
#  type: puppet
#  version: 2.0.0
#  parameters:
#    cwd: /
#    puppet_manifest: puppet/manifests/osd.pp
#    puppet_modules: puppet/modules:/etc/puppet/modules
#    timeout: 3600
#  requires: ['controller','fp-ceph-kraken-ceph-compute']
#  required_for: ['upload_cirros','ceph_ready_check','deploy_end']
#- id: fp-ceph-kraken-osd-lock
#  role: ['ceph-osd']
#  type: puppet
#  version: 2.0.0
#  parameters:
#    puppet_manifest: puppet/manifests/osd_lock.pp
#    puppet_modules: puppet/modules:/etc/puppet/modules
#    timeout: 3600
#  requires: ['fp-ceph-kraken-osd']
#  required_for: ['deploy_end']
- id: fp-ceph-kraken-conf
  role: ['ceph-osd','controller','primary-controller','compute']
  type: puppet
  version: 2.0.0
  parameters:
    puppet_manifest: puppet/manifests/conf.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 3600
  requires: ['post_deployment_start']
  required_for: ['ceph_ready_check']
