- id: ceph-osd
  role: ['ceph-osd']
  type: skipped
  version: 2.0.0
- id: fp-ceph-kraken-ceph-key
  role: ['*']
  type: puppet
  version: 2.0.0
  parameters:
    puppet_manifest: puppet/manifests/ceph_key.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360
  requires: ['deploy_start']
  required_for: ['fp-ceph-kraken-osd']
#- id: fp-ceph-kraken-packages
#  role: ['ceph-osd','controller','primary-controller','compute']
#  type: puppet
#  version: 2.0.0
#  parameters:
#    puppet_manifest: puppet/manifests/packages.pp
#    puppet_modules: puppet/modules:/etc/puppet/modules
#    timeout: 360
#  requires: ['fp-ceph-kraken-ceph-key']
#  required_for: ['ceph-mon']
- id: fp-ceph-kraken-keys
  role: ['ceph-osd']
  type: puppet
  version: 2.0.0
  parameters:
    puppet_manifest: puppet/manifests/keys.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 360
  requires: ['top-role-ceph-osd']
  required_for: ['fp-ceph-kraken-osd']
- id: fp-ceph-kraken-osd
  role: ['ceph-osd']
  type: puppet
  version: 2.0.0
  parameters:
    puppet_manifest: puppet/manifests/osd.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 500
  requires: ['controller','fp-ceph-kraken-keys','fp-ceph-kraken-ceph-key','fp-ceph-kraken-packages']
  required_for: ['upload_cirros','ceph_ready_check','deploy_end']
- id: fp-ceph-kraken-osd-lock
  role: ['ceph-osd']
  type: puppet
  version: 2.0.0
  parameters:
    puppet_manifest: puppet/manifests/osd_lock.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 500
  requires: ['fp-ceph-kraken-osd']
  required_for: ['deploy_end']
- id: fp-ceph-kraken-conf
  role: ['ceph-osd','controller','primary-controller','compute']
  type: puppet
  version: 2.0.0
  parameters:
    puppet_manifest: puppet/manifests/conf.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 500
  requires: ['fp-ceph-kraken-osd-lock']
  required_for: ['ceph_ready_check']
